import Model from "@/models/quizz-model";

describe("QuizzModel", () => {
  describe(".createFromGenerator", () => {
    it("should create a quizz with the choices generated by the generator", () => {
      const choices = ["A", "B", "C", "D"];
      const allChoices = ["A", "B", "C", "D", "E", "F", "G"];
      const generator = { generate: () => ({ choices, allChoices }) };

      const quizz = Model.createFromGenerator(generator);

      expect(quizz.choices).toBe(choices);
      expect(quizz.choicesCount).toBe(4);

      expect(quizz.config.allChoices).toBe(allChoices);
      expect(quizz.config.allChoicesCount).toBe(7);
      expect(quizz.config.generator).toBe(generator);
    });
  
    describe("when creating a quizz without a generator", () => {
      it("should throw an error describing that the `generator` parameter is required", () => {
        expect(() => Model.createFromGenerator()).toThrowError("The `generator` parameter is required to create a quizz");
      });
    });
  });

  describe("#new", () => {
    describe("when creating a quizz without the `choices` configuration", () => {
      it("should throw an error describing that the `choices` configuration is required", () => {
        expect(() => new Model()).toThrowError("The `choices` configuration is required to create a quizz");
      });
    });

    describe("when creating a quizz with an empty `choices` configuration", () => {
      it("should throw an error describing that the `choices` configuration is required", () => {
        expect(() => new Model({ choices: [] })).toThrowError("The `choices` configuration cannot be empty");
      });
    });

    describe("when creating a quizz with a valid `choices` configuration", () => {
      it("should create a quizz with the given choices", () => {
        const choices = ["A", "B", "C", "D"];
        const quizz = new Model({ choices });

        expect(quizz.choices).toBe(choices);
        expect(quizz.choicesCount).toBe(4);

        expect(quizz.config.allChoices).toBe(choices);
        expect(quizz.config.allChoicesCount).toBe(4);
      });

      it('should select an answer from the quizz choices (100 tries)', () => {
        let quizz;
        const choices = ["A", "B", "C", "D", "E", "F", "G"];
        
        for (let i = 0; i < 100; i++) {
          quizz = new Model({ choices });
          
          expect(quizz.choices).toContain(quizz.answer);
        }
      });
    });
  });
});
